"""Added SpeedLimit to Location Model

Revision ID: 391abecaf0e0
Revises: 9fee028b17c3
Create Date: 2025-01-21 22:13:14.729626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391abecaf0e0'
down_revision: Union[str, None] = '9fee028b17c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('speedLimit', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'speedLimit')
    # ### end Alembic commands ###
