"""Update sync feidl in all models

Revision ID: 3f37686ddcb9
Revises: 4951d9a0fb5c
Create Date: 2025-01-23 14:44:32.200991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f37686ddcb9'
down_revision: Union[str, None] = '4951d9a0fb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_model_inputs', sa.Column('sync', sa.Boolean(), nullable=False))
    op.drop_column('ai_model_inputs', 'synced')
    op.add_column('alcohol_questionnaire', sa.Column('sync', sa.Boolean(), nullable=False))
    op.add_column('nlg_report', sa.Column('sync', sa.Boolean(), nullable=False))
    op.drop_column('nlg_report', 'synced')
    op.add_column('roads', sa.Column('sync', sa.Boolean(), nullable=False))
    op.add_column('trip', sa.Column('sync', sa.Boolean(), nullable=False))
    op.drop_column('trip', 'synced')
    op.add_column('unsafe_behaviour', sa.Column('sync', sa.Boolean(), nullable=True))
    op.drop_column('unsafe_behaviour', 'synced')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unsafe_behaviour', sa.Column('synced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('unsafe_behaviour', 'sync')
    op.add_column('trip', sa.Column('synced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('trip', 'sync')
    op.drop_column('roads', 'sync')
    op.add_column('nlg_report', sa.Column('synced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('nlg_report', 'sync')
    op.drop_column('alcohol_questionnaire', 'sync')
    op.add_column('ai_model_inputs', sa.Column('synced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('ai_model_inputs', 'sync')
    # ### end Alembic commands ###
