"""Added Road api code

Revision ID: 408ff5ca4b2b
Revises: b3076df7bfa5
Create Date: 2025-01-21 08:33:37.973953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.uuid import UUIDType


# revision identifiers, used by Alembic.
revision: str = '408ff5ca4b2b'
down_revision: Union[str, None] = 'b3076df7bfa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roads',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('driverProfileId', UUIDType(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('roadType', sa.String(length=100), nullable=False),
    sa.Column('speedLimit', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['driverProfileId'], ['driver_profile.driverProfileId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roads')
    # ### end Alembic commands ###
