"""added influnence to trip model

Revision ID: 8fa88c74b0b4
Revises: 61044d328713
Create Date: 2025-02-17 02:57:58.928999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa88c74b0b4'
down_revision: Union[str, None] = '61044d328713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('influence', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'influence')
    # ### end Alembic commands ###
