"""Created mapper from DriverProfile to Road

Revision ID: 9fee028b17c3
Revises: 50e7147a2977
Create Date: 2025-01-21 11:01:18.444177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fee028b17c3'
down_revision: Union[str, None] = '50e7147a2977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
