"""Changed Driving Tips date type to DateTime

Revision ID: da45a384a8ac
Revises: 3f37686ddcb9
Create Date: 2025-02-04 07:35:44.173897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da45a384a8ac'
down_revision: Union[str, None] = '3f37686ddcb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('raw_sensor_data_ibfk_2', 'raw_sensor_data', type_='foreignkey')
    op.create_foreign_key(None, 'raw_sensor_data', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('trip_ibfk_1', 'trip', type_='foreignkey')
    op.create_foreign_key(None, 'trip', 'driver_profile', ['driverProfileId'], ['driverProfileId'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.create_foreign_key('trip_ibfk_1', 'trip', 'driver_profile', ['driverProfileId'], ['driverProfileId'])
    op.drop_constraint(None, 'raw_sensor_data', type_='foreignkey')
    op.create_foreign_key('raw_sensor_data_ibfk_2', 'raw_sensor_data', 'trip', ['trip_id'], ['id'])
    # ### end Alembic commands ###
