"""add_alcohol_columns_to_trip

Revision ID: f762e9d9b0c9
Revises: af4b0ecbaa2a
Create Date: 2026-01-09 18:38:50.468141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f762e9d9b0c9'
down_revision: Union[str, None] = 'af4b0ecbaa2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_client_ibfk_3', 'api_client', type_='foreignkey')
    op.drop_constraint('api_client_ibfk_2', 'api_client', type_='foreignkey')
    op.create_foreign_key(None, 'api_client', 'insurance_partner', ['insurance_partner_id'], ['id'])
    op.create_foreign_key(None, 'api_client', 'fleet', ['fleet_id'], ['id'])
    op.add_column('trip', sa.Column('alcohol_probability', sa.Float(), nullable=True))
    op.add_column('trip', sa.Column('user_alcohol_response', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'user_alcohol_response')
    op.drop_column('trip', 'alcohol_probability')
    op.drop_constraint(None, 'api_client', type_='foreignkey')
    op.drop_constraint(None, 'api_client', type_='foreignkey')
    op.create_foreign_key('api_client_ibfk_2', 'api_client', 'fleet', ['fleet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('api_client_ibfk_3', 'api_client', 'insurance_partner', ['insurance_partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
